apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-v1
  namespace: v1-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog
      version: v1.0
  template:
    metadata:
      labels:
        app: product-catalog
        version: v1.0
    spec:
      containers:
      - name: app
        image: rachitharajesh/product-catalog:v1.0.0
        ports:
        - containerPort: 9191
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-db.mysql-namespace:3306/productdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 9191
          initialDelaySeconds: 60  # Increase from 30 to 60 or more
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5
